### PR TITLE
Update package.json peerDependencies for React 16 

### PR DESCRIPTION
**Pull request by ric9176**
Following review and comments in #248 (https://github.com/sstur/react-rte/pull/248)

### CODE REVIEW

**Comment by alexlbr** [comment]
👍

**Comment by Majkina** [comment]
👍

**Comment by ric9176** [comment]
@benjy updated 😃

**Comment by chaddjohnson** [comment]
@benjy Thanks! Can we also publish this to npm?

**Comment by benjy** [comment]
Done.

**Comment by eigood** [comment]
Um, how do I install this?  I see no update to the version in package.json, so I can't get this into my local system.  I don't consider this issue closed.

**Pull request merged**
