### PR TITLE
Optimize bundle size.

### LINKED ISSUE #264: react-rte is huge
Hi,

Just had a quick look at our bundle size recently and it seems like react-rte is really huge. It takes around 1MB in our bundle. Any way to make it slimmer ?

Thanks !

screenshot from 2018-01-30 10-10-00

### PR DESCRIPTION
**Pull request by moimael**
Change UglifyJS plugin options to remove comments, don't transpile es6
imports with babel to allow webpack to do tree shaking.
Configure scope hoisting.

fix #264

### CODE REVIEW

**Comment by benjy** [comment]
Thanks, what kind of sizes difference does this make?

Seems to have broken the build though - https://travis-ci.org/sstur/react-rte/builds/337472236

**Comment by moimael** [comment]
It's detailed in the linked issue, from 1.04MB to 385kb which is a pretty huge diff. I'll look at the build failure :)

**Comment by benjy** [comment]
o sorry, missed those the first time, awesome, huge improvement!

**Comment by moimael** [comment]
Found why it failed, this should be fixed now !

**Comment by moimael** [comment]
Would be nice to update all the project dependencies also, we could probably get some more wins there with a newest webpack / babel, ... version.

**Comment by benjy** [comment]
Great thanks, happy to merge this first and then update other dependencies in another PR. Unless you want to update the dependencies first?

**Comment by moimael** [comment]
I think it would be better to do this in another PR :) LGTM !

**Comment by needcaffeine** [comment]
Thank you for getting this merged in!

**Comment by needcaffeine** [comment]
@benjy @moimael Will you please create a new release including this commit?

**Comment by NNSTH** [comment]
yes please- it can be a great improvement since my bundle became huge size...

**Comment by moimael** [comment]
@needcaffeine I don't have the rights to do a new release, but I'd love to see one with this change :)

@benjy Anything I can help with to get this on npm ?

**Comment by benjy** [comment]
I'll push another release out this week.

**Comment by benjy** [comment]
I've pushed a new release, let me know if there are any issues.

**Pull request merged**
