### PR TITLE
[WIP] Image Support

### PR DESCRIPTION
**Pull request by thebritican**
Work-in-progress fix for #6 

Do not merge: The following PRs need to be merged first.

- [x] https://github.com/draft-js-utils/draft-js-utils/pull/12
- [x] https://github.com/sstur/draft-js-export-html/pull/3
- [x] https://github.com/sstur/draft-js-export-markdown/pull/3

GIF progress:

We can use this branch as a base to get the rest of these tasks done, or create small PRs for each and link them here in this description.
- [x] Render based on Entity & Decorator
- [x] Resizing
- [ ] Movement with ImageSpan selection
- [ ] Drag And Drop
- [x] Export
- [x] Import via URL (exact copy of Link Button)
- [ ] Copy / Paste
- [ ] Properly show selection
- [ ] Loading UI
- [ ] Hooks for uploads
- [ ] Attachments

### CODE REVIEW

**Comment by thebritican** [comment]
@sstur so i wrote my own `getBlocksInSelection` function. andddd just discovered that it's in `draft-js-utils`. If you'd like to compare the styles/benchmark that'd be great! I don't really care which implementation we use.

**Comment by frenkelor** [comment]
Hey @sstur , @thebritican I can help you finish this.
Please let me know if you need help .

**Comment by thebritican** [comment]
Feel free to keep up the work on this branch! I mentioned in the corresponding issue some of the blockers with faking selection. Curious what you have in mind for a solution!

**Comment by frenkelor** [comment]
Can you commit to your latest code ?

**Comment by oeddyo** [comment]
Desperately needing this!!! THanks guys

**Comment by ZeroCho** [comment]
Me, too! Any recent news?

**Comment by sstur** [comment]
Sorry for the delay. I'll get back on this as soon as I can find some time. I appreciate you using this editor. I want to keep making it more awesome!

**Comment by magestican** [comment]
Any news on this pull request? I would greatly appreciate it !

**Comment by lidrissi** [comment]
any news please ?

**Comment by bherila** [comment]
If someone wants to work on this, I can merge it to a branch that can be used for further development. Please let me know.

**Comment by bherila** [comment]
Closing in favor of #40, please let me know if this should be reopened.

**Pull request closed without merging**
