### PR TITLE
Image support (continuation of #33)

### PR DESCRIPTION
**Pull request by sstur**
I'm making this a PR to facilitate some discussion around @thebritican's approach (this is mostly his code at this point).

### CODE REVIEW

**Comment by thebritican** [comment]
Perhaps inline images without a selected background is still good enough for some editors? Could this feature be shipped with some resizing logic and paste / drag features? Looking at https://github.com/draft-js-plugins/draft-js-plugins/pull/243 there's a lot of code that can be adapted for resizing and drag and drop. I can try to update this PR with similar code at the end of the week

**Comment by jason-uh** [comment]
What's the state of this PR? Will it get merged soon?

**Comment by ZeroCho** [comment]
@jason-uh I made a package [react-rte-image](https://npmjs.com/package/react-rte-image) which forks this package's image-support branch. You can use it temporarily until this package supports image.

**Comment by jason-uh** [comment]
Thanks, @ZeroCho. I'll check it out.

**Comment by alfonsoperez** [comment]
Any plan to merge anytime soon? :)

**Comment by bherila** [comment]
@alfonsoperez @jason-uh @ZeroCho Could you fix the merge conflict and then I can do a final review pass and merge. Sorry for the delay.

Thanks,
Ben

**Comment by ZeroCho** [comment]
@bherila Did you mean [react-rte-image](https://npmjs.com/package/react-rte-image)? or Do you want me to make a PR on this?

**Comment by bherila** [comment]
Maybe create a PR to pull react-rte-image back to master? I think it would be really nice to bring the forks back in sync with each other, so that as we merge the other community contributions everyone can benefit 😄 

https://github.com/sstur/react-rte/compare/master...ZeroCho:master

**Comment by ZeroCho** [comment]
Okay I'll do it today

**Comment by bherila** [comment]
@ZeroCho thanks, can you advise what the right way to merge this would be? Looks like there is still some conflict

Thanks,
Ben

**Pull request merged**
