### PR TITLE
Closes #282: Improve React ref

### LINKED ISSUE #282: React 16 complains about ref
I'm getting this error with React 16:

```
Element ref was specified as a string (editor) but no owner was set. You may have multiple copies of React loaded.
```

Some research pointed me to https://github.com/sstur/react-rte/blob/master/src/RichTextEditor.js#L148

I'm unable to run the library locally, but switching this to `ref={el => this.editor = el}` and then updating the focus method will do the trick.

### PR DESCRIPTION
**Pull request by vestimir**

### CODE REVIEW

**Comment by vestimir** [comment]
I guess I'll need some help with getting flow checks in place :)

**Comment by sstur** [comment]
Thanks for your contribution @vestimir!

**Comment by santipalenque** [comment]
hey guys, are you publishing this change to npm ?

**Comment by vestimir** [comment]
@sstur can you push a new version that includes the fix to npm?

**Comment by sstur** [comment]
Yes, will do!

**Comment by sstur** [comment]
Oops, there's an issue running the build. Can you check, what happens when you clone down a fresh copy of this repo, run `npm install` and then `npm run build-dist` ?

**Comment by vestimir** [comment]
It fails on my machine, too. Any clues? 

I'm getting this error:

```
 → npm run build-dist

> react-rte@0.16.1 build-dist /Users/vestimir/dev/os/react-rte
> rimraf dist && webpack -p

Hash: 7b2d39f9b177dee525f86022b57510838c958ade
Version: webpack 3.12.0
Child
    Hash: 7b2d39f9b177dee525f8
    Time: 23117ms
           Asset    Size  Chunks                    Chunk Names
    react-rte.js  393 kB       0  [emitted]  [big]  main
     [144] ./src/RichTextEditor.js + 22 modules 59.8 kB {0} [built]
     [292] ./src/ui/Button.css 1.06 kB {0} [built]
     [293] ./node_modules/css-loader??ref--1-1!./src/ui/Button.css 685 bytes {0} [built]
     [297] ./src/ui/IconButton.css 1.07 kB {0} [built]
     [299] ./src/ui/ButtonGroup.css 1.08 kB {0} [built]
     [300] ./node_modules/css-loader??ref--1-1!./src/ui/ButtonGroup.css 796 bytes {0} [built]
     [310] ./src/ui/Dropdown.css 1.07 kB {0} [built]
     [311] ./node_modules/css-loader??ref--1-1!./src/ui/Dropdown.css 1.87 kB {0} [built]
     [312] ./src/lib/EditorToolbar.css 1.08 kB {0} [built]
     [313] ./node_modules/css-loader??ref--1-1!./src/lib/EditorToolbar.css 446 bytes {0} [built]
     [332] ./src/ui/ImageSpan.css 1.07 kB {0} [built]
     [335] ./src/Draft.global.css 1.02 kB {0} [built]
     [336] ./node_modules/raw-loader!./src/Draft.global.css 6.09 kB {0} [built]
     [337] ./src/RichTextEditor.css 1.07 kB {0} [built]
     [338] ./node_modules/css-loader??ref--1-1!./src/RichTextEditor.css 2.08 kB {0} [built]
        + 324 hidden modules
Child
    Hash: 6022b57510838c958ade
    Time: 23104ms
      Asset    Size  Chunks                    Chunk Names
    demo.js  379 kB       0  [emitted]  [big]  main
      [50] ./src/ui/IconButton.js 1.98 kB {0} [built]
      [66] ./src/ui/ButtonGroup.js 334 bytes {0} [built]
      [97] ./src/ui/Dropdown.js 2.79 kB {0} [built]
     [148] ./src/demo.js 319 bytes {0} [built]
     [149] ./src/EditorDemo.js 6.96 kB {0} [built]
     [195] ./src/RichTextEditor.js 13.2 kB {0} [built]
     [299] ./src/lib/EditorToolbar.js 16.3 kB {0} [built]
     [309] ./src/ui/ButtonWrap.js 332 bytes {0} [built]
     [312] ./src/ui/IconButton.css 1.07 kB {0} [built]
     [316] ./src/ui/ButtonGroup.css 1.08 kB {0} [built]
     [327] ./src/ui/Dropdown.css 1.07 kB {0} [built]
     [333] ./src/lib/EditorValue.js 3.36 kB {0} [built]
     [350] ./src/lib/LinkDecorator.js 758 bytes {0} [built]
     [351] ./src/lib/ImageDecorator.js 545 bytes {0} [built]
     [359] ./src/RichTextEditor.css 1.07 kB {0} [built]
        + 346 hidden modules

    ERROR in ./node_modules/draft-js/lib/DraftEditorTextNode.react.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditorTextNode.react.js 22:12-28
     @ ./node_modules/draft-js/lib/DraftEditorLeaf.react.js
     @ ./node_modules/draft-js/lib/DraftEditorBlock.react.js
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditorContents-core.react.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditorContents-core.react.js 29:12-28
     @ ./node_modules/draft-js/lib/DraftEditorContents.react.js
     @ ./node_modules/draft-js/lib/DraftEditor.react.js
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditorLeaf.react.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditorLeaf.react.js 25:12-28
     @ ./node_modules/draft-js/lib/DraftEditorBlock.react.js
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditorPlaceholder.react.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditorPlaceholder.react.js 22:12-28
     @ ./node_modules/draft-js/lib/DraftEditor.react.js
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditorBlock.react.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditorBlock.react.js 28:12-28
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditor.react.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditor.react.js 35:12-28
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DefaultDraftBlockRenderMap.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DefaultDraftBlockRenderMap.js 19:12-28
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/demo.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src'
     @ ./src/demo.js 1:0-26

    ERROR in ./src/EditorDemo.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src'
     @ ./src/EditorDemo.js 8:0-41
     @ ./src/demo.js

    ERROR in ./src/RichTextEditor.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src'
     @ ./src/RichTextEditor.js 10:0-41
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/lib/EditorToolbar.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/lib'
     @ ./src/lib/EditorToolbar.js 13:0-41
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/lib/StyleButton.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/lib'
     @ ./src/lib/StyleButton.js 8:0-41
     @ ./src/lib/EditorToolbar.js
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/lib/LinkDecorator.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/lib'
     @ ./src/lib/LinkDecorator.js 1:0-26
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/Button.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/Button.js 8:0-41
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/ButtonWrap.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/ButtonWrap.js 2:0-26
     @ ./src/ui/IconButton.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/PopoverIconButton.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/PopoverIconButton.js 8:0-41
     @ ./src/lib/EditorToolbar.js
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/ImageSpan.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/ImageSpan.js 8:0-41
     @ ./src/lib/ImageDecorator.js
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/IconButton.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/IconButton.js 9:0-41
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/Dropdown.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/Dropdown.js 10:0-41
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/InputPopover.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/InputPopover.js 6:0-41
     @ ./src/ui/PopoverIconButton.js
     @ ./src/lib/EditorToolbar.js
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/ButtonGroup.js
    Module not found: Error: Can't resolve 'react' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/ButtonGroup.js 2:0-26
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditorLeaf.react.js
    Module not found: Error: Can't resolve 'react-dom' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditorLeaf.react.js 26:15-35
     @ ./node_modules/draft-js/lib/DraftEditorBlock.react.js
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditor.react.js
    Module not found: Error: Can't resolve 'react-dom' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditor.react.js 36:15-35
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/editOnSelect.js
    Module not found: Error: Can't resolve 'react-dom' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/editOnSelect.js 17:15-35
     @ ./node_modules/draft-js/lib/DraftEditorEditHandler.js
     @ ./node_modules/draft-js/lib/DraftEditor.react.js
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditorTextNode.react.js
    Module not found: Error: Can't resolve 'react-dom' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditorTextNode.react.js 23:15-35
     @ ./node_modules/draft-js/lib/DraftEditorLeaf.react.js
     @ ./node_modules/draft-js/lib/DraftEditorBlock.react.js
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./node_modules/draft-js/lib/DraftEditorBlock.react.js
    Module not found: Error: Can't resolve 'react-dom' in '/Users/vestimir/dev/os/react-rte/node_modules/draft-js/lib'
     @ ./node_modules/draft-js/lib/DraftEditorBlock.react.js 29:15-35
     @ ./node_modules/draft-js/lib/Draft.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/demo.js
    Module not found: Error: Can't resolve 'react-dom' in '/Users/vestimir/dev/os/react-rte/src'
     @ ./src/demo.js 2:0-33

    ERROR in ./src/lib/EditorToolbar.js
    Module not found: Error: Can't resolve 'react-dom' in '/Users/vestimir/dev/os/react-rte/src/lib'
     @ ./src/lib/EditorToolbar.js 14:0-33
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js

    ERROR in ./src/ui/InputPopover.js
    Module not found: Error: Can't resolve 'react-dom' in '/Users/vestimir/dev/os/react-rte/src/ui'
     @ ./src/ui/InputPopover.js 7:0-33
     @ ./src/ui/PopoverIconButton.js
     @ ./src/lib/EditorToolbar.js
     @ ./src/RichTextEditor.js
     @ ./src/EditorDemo.js
     @ ./src/demo.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! react-rte@0.16.1 build-dist: `rimraf dist && webpack -p`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the react-rte@0.16.1 build-dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vestimir/.npm/_logs/2018-08-15T09_07_13_008Z-debug.log
```

**Pull request merged**
