### PR TITLE
Add webpack.DefinePlugin

### PR DESCRIPTION
**Pull request by ZeroCho**
Related with #104

### CODE REVIEW

**Comment by sstur** [comment]
CI not passing : (
https://travis-ci.org/sstur/react-rte/builds/168974037

**Comment by ZeroCho** [comment]
Oops... little eslint problems... Fixing now

**Comment by ZeroCho** [comment]
@sstur Done! So many updates today! Very hard for react-rte-image to follow up!

**Comment by skolmer** [comment]
@ZeroCho Thanks! You could automate the dependency updates with greenkeeper.io

**Comment by sstur** [comment]
Yes, lots of updates today : )
I really want to get the image features in here so you don't have to maintain a fork. Hopefully soon..

**Pull request merged**
