### PR TITLE
added typescript definition file

### PR DESCRIPTION
**Pull request by jclyons52**
I made a definition file for a project that I was working on and figured I'd share it. I haven't done much testing yet with a consuming package, but if you're willing to merge it I'll set up a yarn workspace and double check everything.

### CODE REVIEW

**Comment by baorv** [comment]
This project is still active?

**Comment by chrisBetances** [comment]
Is there any possibility that this could be validated and merged in soon?  I am really looking to use this tool and it not working with typescript is holding me back

**Comment by baorv** [comment]
@chrisBetances, I think you should fork and add commits from @jclyons52.

**Comment by baorv** [comment]
Maybe, this repo isn't maintained.

**Comment by jclyons52** [comment]
since it looks like there's some interest in this and the repo isn't maintained I'll submit it to definitely typed this weekend. that way it will be available as `@types/react-rte`

**Comment by baorv** [comment]
Thank for sharing @jclyons52. I hope it gets published soon.

**Comment by chrisBetances** [comment]
That's awesome.  can you expand it to the markdown variants also?

**Comment by jclyons52** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31247

**Comment by baorv** [comment]
Thank you @jclyons52

**Comment by jclyons52** [comment]
pr has been merged into definitely typed. Try it out and let me know if there are any issues

**Pull request closed without merging**
