### PR TITLE
Add autoFocus prop to support automatically focusing editor on mounting

### PR DESCRIPTION
**Pull request by UberMouse**
Hi there,

We need support in our project to have the Editor autofocus once it's mounted, so I've gone ahead and made the changes. Let me know if you have any issues with this approach.

ESLint is passing but I'm getting a bunch of Flow errors about `Duplicate module provider`, unsure if I'm doing something wrong.

Cheers,
Taylor

---
This change is [Reviewable](https://reviewable.io/reviews/sstur/react-rte/117)

### CODE REVIEW

**Comment by sstur** [comment]
Hi Taylor. Thank you for your contribution. Would you mind following up with a PR to document this feature in the README?

**Comment by UberMouse** [comment]
Hey @sstur,

Any ETA on when this will be published on NPM? 

Cheers

**Comment by sstur** [comment]
Done.

**Comment by UberMouse** [comment]
Awesome, thanks :)

**Pull request merged**
